#FROM alpine/node:22.14.0
FROM node:22.14.0-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE ${PORT}
#CMD ["npm", "run", "build-and-start"]
CMD ["npm", "run", "dev"]

#ENTRYPOINT ["top", "-b"]